### ISSUE TITLE
Resolve timezone issue in docker file

### ISSUE THREAD

**Issue by shaju007** [paslandau/coding-challenge-setup#8]
I think due daylight saving time settings I am facing issue while running `make docker-setup` in my machine (Windows10 Pro). @pascallandau-ay Can you please check?
![Screenshot_5](https://user-images.githubusercontent.com/22970269/141657464-86846515-13e8-412d-a4aa-cb8e2fe6d490.png)

**Comment by pascallandau-ay** [comment]
Hey @shaju007 

not sure is actually a timezone issue - feels more like a general docker issue.

However, I just updated a couple of things in #9 and also did some general cleanup (like removing setting the timezone explicitly). 

Please try again. You might want to run `make docker-prune` to ensure you have a "clean slate" - though this command will also remove any other docker images on your machine, so please use carefully.

Cheers
Pascal

**Comment by shaju007** [comment]
Hey @pascallandau-ay 

Thanks for updating the code.

Now I am getting new error, `#10 0.431 /bin/bash: /tmp/scripts/create_user.sh: /bin/sh^M: bad interpreter: No such file or directory`. I am not sure if this is related to fileformat of the script file, [link](https://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter)
![Screenshot_6](https://user-images.githubusercontent.com/22970269/141680777-0556a073-b50b-4049-85fa-f3bf7a97e571.png)

**Comment by shaju007** [comment]
I also tried changing `#!/bin/sh` to `#!/bin/bash`, didn't help.

**Comment by pascallandau-ay** [comment]
Wild guess: 
- your `git` is configured to convert Unix line endings (`\n`) to windows line endings (`\r\n`) - see the related thread https://stackoverflow.com/questions/39527571/are-shell-scripts-sensitive-to-encoding-and-line-endings
- when you checked out the code, the line endings have been converted from `\n` to `\r\n`
- e.g. in `.docker/.shared/scripts/create_user.sh` from
  ```
  #!/bin/sh\n
  ```
   to 
  ```
  #!/bin/sh\r\n
  ```
- so docker now reads `/bin/sh\r` - which doesn't exist

**Comment by shaju007** [comment]
Thanks a lot @pascallandau-ay 
I have fixed the problem, your guess is right.
